source "https://rubygems.org"

gem "capybara", "3.13.2"
gem "cucumber", "3.1.2"
gem "httparty"
gem "rspec", "3.8.0"
gem "json_matchers"

group :development do
  gem "byebug", "11.0.0"
  gem "pry-byebug", "3.7.0"
end